### ISSUE TITLE
Reputation does not influence multiplier

### ISSUE THREAD

**Issue by Harald92** [koreisha/anomaly-faction-economy#2]
I tested and setup a spreadsheet to calculate the multiplier for the item cost and noticed that:

1. The calculation for the reputation boni to the multiplier is setup that you would get to much of a boni when you get up to Legendary rank (50000 Reputation)
2. The above does not matter because the multiplier does not get changed by reputation at the moment.

**Comment by Harald92** [comment]
ADDITION: the "heavy_pockets" achievement buff for price does not work in the right way. When you get the achievement you get less for stuff you sell and have to pay more for stuff.

EDIT: When you setup the achievement calculation for the multiplier the same way you do for all the previous calculations it works. So instead of this on in line 105:

    multiplier = game_statistics.has_actor_achievement("heavy_pockets") and multiplier - 0.3 or multiplier

You do

    multiplier = game_statistics.has_actor_achievement("heavy_pockets") and multiplier * (1 + (0.3)) or multiplier

If you are fancy you could even add a MCM setting for it

**Comment by koreisha** [comment]
1. You're confusing reputation with rank. Rep is good\bad\terrible etc. and was working properly.

2. Idea behind heavy pockets was that traders would try to scam player if they know that they're filthy rich (from gameplay perspective - late game got too easy with big rep and goodwill multipliers, so this serves as the way to make it harder). Maybe it could use an MCM option in the future when I get back to working on this mod.

**Comment by Harald92** [comment]
1. Yeah you are right, I thought it meant the rank. I need to look into that again then. So the factors which influence prices are the relation from your faction to the vendors (Faction discount), your goodwill to the faction (goodwill factor) and the actors reputation to the vendors (Reputation). I need to look into where I can get that to test how much it influences the price to apply it to my spreadsheet ^^.
2. I had the feeling that this was the intention but it felt bad because even if you are poor again you get punished because you were rich once, but the other way around is weird too because you get better prices because you are rich ^^.
